name: PixelsPointsPolygons
size: ${..encoder.in_size}
in_path: /mnt/DATA/IMANE/p3_NY_full/data/224
out_path: /mnt/DATA/IMANE/PixelsPointsPolygons_output
annotation_type: blocks
country: NY
annotations:
  train: /mnt/DATA/IMANE/p3_NY_full/data/224/annotations/blocks/annotations_NY_train.json
  val:   /mnt/DATA/IMANE/p3_NY_full/data/224/annotations/blocks/annotations_NY_val.json
  test:  /mnt/DATA/IMANE/p3_NY_full/data/224/annotations/blocks/annotations_NY_test.json
ffl_stats:
  train: ${..in_path}/ffl/train/stats-${..country}.pt
  val:   ${..in_path}/ffl/val/stats-${..country}.pt
  test:  ${..in_path}/ffl/test/stats-${..country}.pt
train_subset: ${...run_type.train_subset}
val_subset: ${...run_type.val_subset}
test_subset: ${...run_type.test_subset}